---
title: "Welcome!"
description: |
  Welcome to my new blog, Data Science & Economics. I hope you enjoy reading my content.
author:
  - name: David Heilbron 
    url: https://davidheilbron.com
date: 08-05-2025
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

My name is David, I'm an Economist from Icesi University in Cali, Colombia and a Data Scientist from the University of Milan. This blog is an attempt to bring out topics of my interest and domain and make them available to the public.

This is the first time I write a blog, so there's a lot of learning going on right now. I don't consider myself an expert in Economics or Data Science, but a day-to-day citizen willing to learn by doing and to give its two cents to the plethora of available knowledge in the internet.

I will try my best to be original and give it my own twist, hopefully I can print (?) my values and skills into the blog, thus proposing discussions, stating my views, and hopefully, inspiring others.

As a personal side note, I consider people (myself included) nowadays got used to have a passive role in society, not expressing their thoughts, not committing to anything, not exposing themselves or taking risks, not having uncomfortable conversations. I can't control the world, but I can definitely chose the path I want for my life, and writing is part of it.

I'm from Cali, Colombia. Based in Munich, Germany.
